# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Unknwon/com"
  version = "1.0.1"

[[constraint]]
  name = "github.com/c3sr/config"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/ldcache"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/logger"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/model"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/nvidia-smi"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/utils"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/uuid"
  version = "0.1.0"

[[constraint]]
  name = "github.com/c3sr/vipertags"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/carlescere/scheduler"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "=4.0.2"

[[constraint]]
  name = "github.com/docker/docker"
  version = "19.3.5"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/go-plugins-helpers"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/flyaways/golang-lru"
  version = "0.1.0"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.11"

[[constraint]]
  branch = "master"
  name = "github.com/junegunn/go-shellwords"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "3.0.7"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "0.1.1"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.6.1"

[[constraint]]
  name = "go.uber.org/goleak"
  version = "1.1.10"

[prune]
  go-tests = true
  unused-packages = true
